# Settings for the app
app:
  # HTML Title
  title: Make Brooklyn Safer
  # Header name
  name: Kids Rely On Safe Streets
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.68948969132277
      lng: -73.96614074707031
    zoom: 15
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/precincts.geojson
      type: json
      rules:
        - condition: '{{Precinct}} === 88'
          style:
            color: "#fff"
            opacity: 0.6
            fillOpacity: 0
            weight: 1
        - condition: '{{Precinct}} !== 88'
          style:
            color: "#000"
            opacity: 0.6
            fillOpacity: 0.5
            weight: 1


# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  landmark:
    label: _(Landmark)
    rules:
      - condition: '"{{location_type}}" === "Traffic_does_not_yield"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Bike_lane_blocked"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "No_bike_lane"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Speeding_traffic"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]      
      - condition: '"{{location_type}}" === "Not_enough_time_to_cross"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Dangerous_crossing"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Crosswalk_blocked"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]    
      - condition: '"{{location_type}}" === "Crosswalk_needs_painting"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Sidewalk_too_narrow"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]
      - condition: '"{{location_type}}" === "Double_parked_cars"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17,18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [17,18]
          shadowSize: [17,18]
          iconAnchor: [12, 41]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Identify a problem)
  action_text: _(added)
  title: _(Describe the issue)
  action_text: _(identified)
  anonymous_name: _(Someone)
  submit_button_label: _(Share this report)
  items:
    - prompt: _(Your name)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(What is the problem here?)
      type: select
      name: location_type
      options:
        - label: _(Traffic does not yield)
          value: Traffic_does_not_yield
        - label: _(Bike lane blocked)
          value: Bike_lane_blocked
        - label: _(No bike lane)
          value: No_bike_lane
        - label: _(Speeding traffic)
          value: Speeding_traffic
        - label: _(Not enough time to cross)
          value: Not_enough_time_to_cross
        - label: _(Dangerous crossing)
          value: Dangerous_crossing
        - label: _(Crosswalk blocked)
          value: Crosswalk_blocked
        - label: _(Crosswalk needs painting)
          value: Crosswalk_needs_painting
        - label: _(Sidewalk too narrow)
          value: Sidewalk_too_narrow
        - label: _(Double parked cars/trucks)
          value: Double_parked_cars
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Tell us more)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Optionally, tell us more about this location...)
    - prompt: _(Share an image showing the problem)
      inputfile_label: _(Add an image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
    
  - title: _(Resources)
    slug: resources
    name: features